<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>RxJS exercise 6</title>
</head>

<body>
    <script src="https://unpkg.com/rxjs@7.5.6/dist/bundles/rxjs.umd.min.js"></script>
    <script>
        // Exercise 6;
        // Part A:
        // This Observable does not complete right now. We want Observables to handle errors and complete naturally.
        // Hint: Run the example first and check the console log.
        //
        // Part B:
        // Rewrite this code so you don't need a Subject anymore.
        // Hint: the `from` creator and the `map` operator could help here.

        const { Subject } = rxjs;

        const numbersArray = [0, 1, 2, 3, 4];
        const numbersSubject = new Subject();

        numbersSubject.subscribe(
            next => {
                console.log(next);
            }, 
            error => {
                console.error(error);
            }, 
            () => {
                console.info('Subscription finished');
            }
        );

        numbersArray.forEach(number => {
            // we have some business logic over here that we want to keep
            if (number === 3) {
                numbersSubject.error('Number 3 is way too high!');
            }

            numbersSubject.next(number);
        });
    </script>
</body>

</html>